name: Compile Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Mengetes di 3 board utama yang didukung library
        board: [ "arduino:avr:uno", "esp8266:esp8266:nodemcuv2", "esp32:esp32:esp32" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platforms
        run: |
          if [[ "${{ matrix.board }}" == *"avr"* ]]; then
            arduino-cli core install arduino:avr
          elif [[ "${{ matrix.board }}" == *"esp8266"* ]]; then
            arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
            arduino-cli core install esp8266:esp8266 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          elif [[ "${{ matrix.board }}" == *"esp32"* ]]; then
            arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          fi

      - name: Compile Library Examples
        run: |
          # Membuat folder library agar arduino-cli bisa menemukannya
          mkdir -p $HOME/Arduino/libraries/IskakINO_Storage
          cp -r . $HOME/Arduino/libraries/IskakINO_Storage/
          
          # Compile contoh HybridDemo.ino
          arduino-cli compile --fqbn ${{ matrix.board }} examples/HybridDemo/HybridDemo.ino
